[package]
name = "display_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.crossterm]
version = "0.23"
features = ["event-stream"] 
